export const CHANGE_BANNER = 'recommand/CHANGE_BANNER'
export const CHANGE_RECOMMEND_LIST = 'recommand/CHANGE_RECOMMEND_LIST'
export const CHANGE_RECOMMEND_LOADING = 'recommand/CHANGE_RECOMMEND_LOADING'